---
- name: install MySQL package
  apt: pkg={{item}} state=installed update_cache=true
  with_items:
    - mysql-server
    - python-mysqldb

- name: create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: 
  - restart mysql

- name: start Mysql Service
  service: name=mysql state=started enabled=yes
